apiVersion: dashboard.opendatahub.io/v1alpha1
kind: HardwareProfile
metadata:
  name: all-nvidia-mig
  namespace: redhat-ods-applications
spec:
  description: Nvidia GPU - GPU Type / MIG / Profile
  displayName: Nvidia GPU - MIG Profile
  enabled: true
  nodeSelector:
    nvidia.com/gpu.present: "true"
    nvidia.com/mig.config: all-1g.5gb
    # node.kubernetes.io/instance-type: g4dn.4xlarge
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      operator: Exists
  identifiers:
    - defaultCount: '1'
      displayName: CPU
      identifier: cpu
      # maxCount: '6'
      minCount: '1'
      resourceType: CPU
    - defaultCount: 4Gi
      displayName: Memory
      identifier: memory
      # maxCount: 24Gi
      minCount: 4Gi
      resourceType: Memory
