---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fix-operator-scale
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fix-operator-scale
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
    verbs:
      - '*'
      # - get
      # - list
      # - patch
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - get
      - list
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fix-operator-scale
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
subjects:
  - kind: ServiceAccount
    name: fix-operator-scale
    namespace: redhat-ods-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fix-operator-scale
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fix-operator-scale
  namespace: redhat-ods-operator
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "11"
spec:
  template:
    spec:
      containers:
        - name: minion
          image: registry.redhat.io/openshift4/ose-cli
          command:
            - /bin/bash
            - -c
            - /scripts/job.sh
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: fix-operator-scale
            defaultMode: 0755
      restartPolicy: Never
      serviceAccount: fix-operator-scale
      serviceAccountName: fix-operator-scale
  backoffLimit: 4
