apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
- job.yaml

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/hook: PreSync

configMapGenerator:
  - name: fix-operator-scale
    namespace: redhat-ods-operator
    files:
      - job.sh
