apiVersion: infrastructure.opendatahub.io/v1alpha1
kind: HardwareProfile
metadata:
  annotations:
    opendatahub.io/dashboard-feature-visibility: '["workbench"]'
    opendatahub.io/disabled: "false"
    opendatahub.io/display-name: Small
  name: demo-sized
  namespace: demo-notebooks
spec:
  identifiers:
  - defaultCount: "1"
    displayName: CPU
    identifier: cpu
    maxCount: "2"
    minCount: "1"
    resourceType: CPU
  - defaultCount: 4Gi
    displayName: Memory
    identifier: memory
    maxCount: 8Gi
    minCount: 4Gi
    resourceType: Memory
