# oc-mirror -c ./isc.yaml --workspace file:///${PWD}/scratch/oc-mirror docker://registry:5000 --v2 --image-timeout 60m
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.18
      minVersion: 4.18.22
      maxVersion: 4.18.22
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.18
      targetCatalog: docker://localhost/vendor/redhat-operator-index
      # targetTag: v4.18
      packages:
        - name: nfd
    # - catalog: registry.redhat.io/redhat/certified-operator-index:v4.18
    #   targetCatalog: vendor/certified-operator-index
    #   targetTag: 'v4.18'
    #   packages:
    #     - name: gpu-operator-certified
    #       defaultChannel: v25.3
    #       channels:
    #       - name: v25.3
    #         minVersion: 25.3.4
    #         maxVersion: 25.3.4
  # additionalImages:
